### ISSUE TITLE
Get X-DC from X-DC-plugin and route to service by x-dc header not working 

### ISSUE THREAD

**Issue by sreekesh93** [datawire/plugin-poc#11]
I have an understanding that based on the filter policy attached here it will route request to x-dc-plugin. The x-dc plugin will set the x-dc header and return the request. I have added a mapping to route request  to different service based on x-dc header, but the request are not routed as expected.
**Filter& filterPolicy**
```
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: "x-dc-filter" 
spec:
  Plugin:
    name: "x-dc-plugin"
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: "x-dc-filter-policy"
spec:
  rules:
  - host: "*"
    path: /
    filters:               
    - name: "x-dc-filter"  

```
I have updated the x-dc-plugin.go and returned x-dc as 1 or 2, build the code as per readme doc and tested using aes-plugin-runner (plugin working as expected). 
eg: plugin code 
```...
     ...
     ...
	keyInt, err := strconv.Atoi(realmId[0])
	if keyInt%2 == 0 {
		w.Header().Set("X-DC", "1")
	} else {
		w.Header().Set("X-DC", "2")
	}

	w.WriteHeader(http.StatusOK) 
```
**mapping:**
```
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  labels:
    product: aes
    app.kubernetes.io/component: ambassador-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  dc_1_mapping
      prefix: /
      headers:
        x-dc: 1
      service: testservice1:8081
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  dc_2_mapping
      prefix: /
      headers:
        x-dc: 2
      service: testservice2:8082
      ---
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    service: ambassador
```
